services:
    poc.controller.auth:
        class: AppBundle\Controller\AuthController
        arguments:
            - "@form.factory"
            - "@event_dispatcher"
            - "@token_generator"
            - "%jwt.secret.key%"

    poc.controller.cats:
        class: AppBundle\Controller\CatsController
        arguments:
            - "@templating"
            - "@doctrine_mongodb.odm.document_manager"
            - "@form.factory"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@cat.repository"
            - "@cat.generator"
